#!/bin/bash

# Mock aria2c command to retrieve files.
#
# Author: Andres Gomez
# Verison: 2025-07-12

#set -xv
# Fails when a variable is not initialized.
set -u
# Fails with an non-zero return code.
set -e
# Fails if the commands of a pipe return non-zero.
set -o pipefail
# Fails if an internal function fails.
set -E

LOG=/tmp/mock_aria2c.log

# Base directory for the project.
declare SCRIPT_BASE_DIRECTORY
SCRIPT_BASE_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." \
  &> /dev/null && pwd)"
readonly SCRIPT_BASE_DIRECTORY

# Loads the global properties.
# shellcheck source=../etc/properties.sh
source "${SCRIPT_BASE_DIRECTORY}/etc/properties.sh"

echo "====" >> "${LOG}"
date  >> "${LOG}"
echo "Parameters: ${@}" >> "${LOG}"
# No params
if [[ -z "${1:-}" ]]; then
 echo "This is a mock aria2c command."

# aria2c --version
elif [[ "${1}" == "--version" ]]; then
 echo "Mock aria2c for OSM Notes Profile"

# Retrieves Planet notes dump file
# planet-notes-latest.osn.bz2
elif [[ "${1}" == "-d" ]] \
  && [[ "${3}" == "-o" ]] \
  && [[ "${4}" == "planet-notes-latest.osn.bz2" ]] \
  && [[ "${5}" == "-x" ]] \
  && [[ "${6}" == "8" ]] \
  && [[ "${7}" == "${PLANET}/notes/planet-notes-latest.osn.bz2" ]]; then
 cp "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.bz2" \
   "${2}/${4}"
 echo "planet" >> "${LOG}"

else
 echo "ERROR: Invalid parameter for mock aria2c."
 echo "error" >> "${LOG}"
fi
