#!/bin/bash

# Mock aria2c command to retrieve files.
#
# Author: Andres Gomez
# Verison: 2025-07-12

#set -xv
# Fails when a variable is not initialized.
set -u
# Fails with an non-zero return code.
set -e
# Fails if the commands of a pipe return non-zero.
set -o pipefail
# Fails if an internal function fails.
set -E

# aria2c --version
if [[ "${1}" == "--version" ]]; then
 echo "Mock aria2c for OSM Notes Profile"

# Retrieves Planet notes dump file
# planet-notes-latest.osn.bz2
elif [[ "${1}" == "-O" ]]
  && [[ "${2:(-31)}" == "planet-notes-latest.osn.bz2" ]] \
  && [[ "${3}" == "${PLANET}/notes/planet-notes-latest.osn.bz2" ]]; then
 cp "${SCRIPT_BASE_DIRECTORY}/test/extra/mockPlanetDump.osn.bz2" "${2}"
# ToDo Copiar el osn en el directorio extra

else
 echo "ERROR: Invalid parameter for mock aria2c."
fi
