#!/bin/bash

# Reset status for mock files
#
# Author: Andres Gomez
# Verison: 2025-07-14

#set -xv
# Fails when a variable is not initialized.
set -u
# Fails with an non-zero return code.
set -e
# Fails if the commands of a pipe return non-zero.
set -o pipefail
# Fails if an internal function fails.
set -E

# File for multiple API calls with consecutive calls.
COUNTS_FILE_API="/tmp/mock_wget_counts"

# Base directory for the project.
declare SCRIPT_BASE_DIRECTORY
SCRIPT_BASE_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." \
 &> /dev/null && pwd)"

# Removes count file for API.
rm -f "${COUNTS_FILE_API}"

# Regenerates compress file and md5.
rm -f "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn" \
  "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.bz2" \
  "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.bz2.md5"

cp "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.xml" \
  "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn"
bzip2 "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn"
md5sum "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.bz2" \
  > "${SCRIPT_BASE_DIRECTORY}/test/command/extra/mockPlanetDump.osn.bz2.md5"

echo "Current Path value"
echo "${PATH}"
export PATH="${SCRIPT_BASE_DIRECTORY}/test/command/:${PATH}"
echo "export PATH=\"${SCRIPT_BASE_DIRECTORY}/test/command/:${PATH}\""

