#!/bin/bash

# Reset status for mock files
#
# Author: Andres Gomez
# Verison: 2025-07-12

#set -xv
# Fails when a variable is not initialized.
set -u
# Fails with an non-zero return code.
set -e
# Fails if the commands of a pipe return non-zero.
set -o pipefail
# Fails if an internal function fails.
set -E

COUNTS_FILE_API="/tmp/mock_wget_counts"

# Removes count file for API.
rm -f $"{COUNTS_FILE_API}"

# Regenerates compress file and md5.
bzip2 -k "${SCRIPT_BASE_DIRECTORY}/test/extra/mockPlanetDump.osn"
md5sum "${SCRIPT_BASE_DIRECTORY}/test/extra/mockPlanetDump.osn.bz2" \
  > "${SCRIPT_BASE_DIRECTORY}/test/extra/mockPlanetDump.osn.bz2.md5"